name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read

    concurrency:
      group: "test @ ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: configure git for tests
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com

      - run: go test ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
